### ISSUE TITLE
XCSoar doesn't start

### ISSUE THREAD

**Issue by kedder** [Openvario/meta-openvario#207]
On the latest `hardknott` image  (1e1c6a9), XCSoar fails to start. The device shows this message on screen:

```
Using DRI device /dev/dri/card0 (use environment variable DRI_DEVICE to override)
drmModeGetResources() failed
```

After few seconds the main menu appears.

The issue is reported in #204 by @lordfolken. It is possible to run XCSoar from command line with `DRI_DEVICE=/dev/drm/dri/card1` environment variable.

**Comment by MaxKellermann** [comment]
Fixed in xcsoar-testing (-> 7.23)

**Comment by lordfolken** [comment]
What do we do here? Do we wait until 7.23 is released? This bug is still in the current master.

**Comment by MaxKellermann** [comment]
Yes. I think the next XCSoar release will be long before the next OpenVario release.

**Comment by lordfolken** [comment]
thren at least the bug report should stay open, as there is still a change needed in meta-openvario.

**Comment by linuxianer99** [comment]
ok ... you are right ... sorry ...

**Comment by MaxKellermann** [comment]
https://github.com/Openvario/meta-openvario/pull/268
